### PR TITLE
Allow for the configuration of allowed headers.

### PR DESCRIPTION
**Pull request by veelci**

### CODE REVIEW

**Comment by veelci** [comment]
@ojacobson, any updates on this?

**Comment by ojacobson** [comment]
Any chance I can get you to add your name to the list in CONTRIBUTORS.md?

Sorry about the delay on this. Winter sucks and I hate it. I've brought the project up to date so that it's easy to release, and I should be able to get this out the door as soon as you sign off on the MIT license.

**Comment by veelci** [comment]
OK - Done.

**Comment by ojacobson** [comment]
Thanks a ton. This should hit jcenter as version 0.1.0 shortly.

In the future, I'll try to be considerably more timely about contributions. Thanks for being gentle with an unreasonably-long delay handling this PR.

**Pull request merged**
